const trainersData = [
  {
    id: 1,
    title: "nutrition consultant avishag",
    name: "אבישג סולומון",
    profileImg: "/img/avishagtrainer.avif",
    pageImg: "/img/trainersPage/avishagTrainerPage.avif",
    aboutPage: "/trainers",
    instagramPage: "https://www.instagram.com/shoogiz__/",
    facebookPage: "https://www.facebook.com/avishag.solomon.7",
    description: "ספורט לא תמיד היה חלק מחיי, ולא תמיד הייתי רזה או חטובה. את הספורט הכרתי כנקודת מפנה בחייל בגיל 12 , כאשר קיבלתי החלטה לראשונה בחיי להשתנות ובכך מילד דחויה, מלאה וללא ביטחון, הצלחתי באמצעות הספורט והתזונה לשנות את חיי",
    course1: "תואר ראשון בפסיכולוגיית ספורט ומדעי ההתנהגות, מטעם המכללה האקדמית תל אביב יפו",
    course2: "ייעוץ ותזונת ספורט וארוח חיים בריא, מטעם המכללה האקדמית וינגייט",
    course3: "מדריכת כושר גופני ואימון קטינים, מטעם מכון וינגייט",
    course4: "התמחות - מדריכת כושר לילדים וטיפול בעודף משקל, מטעם המכללה האקדמית וינגייט",
    story1: "פירות יבשים והסגולות שלהם",
    hrefStory1: "https://www.israelbody.org/articles/dried-fruit-1"
  },
  {
    id: 2,
    title: "nutrition consultant tamir",
    name: "תמיר דזן",
    profileImg: "/img/tamirtrainer.avif",
    pageImg: "/img/trainersPage/tamirTrainerPage.avif",
    aboutPage: "/trainers",
    instagramPage: "https://www.instagram.com/tamirdazan/",
    facebookPage: "https://www.facebook.com/tamir.dazan/",
    description: "מאמן חדר כושר מוסמך ומפתח גוף תחרותי לשעבר זוכה מקום ראשון מר ישראל. בוגר קורס תזונה וספורט במכללה האקדמית של וינגייט. אני מתמחה בחיטוב ועיצוב הגוף, עלייה במסת השריר וחיטוב גם ברמה התחרותית לספורטאים טבעיים, בן השאר עוסק גם בהרכבת תפריטים לצמחוניים וטבעוניים.",
    course1: "מאמני חדר כושר ואימון קטינים - קמפוס שיאים",
    course2: "תזונת ספורט - היבטיים מטבוליים בתזונת ספורט ופעילות גופנית - הדר יוסף תל אביב (המכללה האקדמית בוינגייט)",
    story1: "חלבונים - כמה? מתי? איך? כל התשובות",
    story2: "שורפי שומן טבעיים",
    story3: "!לרשימת כל הכתבות שלי - לחצו כאן",
    hrefStory1: "https://www.israelbody.org/articles/protein-all-the-answers",
    hrefStory2: "https://www.israelbody.org/articles/natural-fat-burners",
    hrefStory3: "https://www.israelbody.org/tags/tamir-dazan"

  },
  { id: 3,
    title: "nutrition consultant yuval",
    name: "יובל וכטרמן",
    profileImg: "/img/yuvaltrainer.avif",
    pageImg: "/img/trainersPage/yuvalTrainerPage.avif",
    aboutPage: "/trainers",
    instagramPage: "https://www.instagram.com/yuval_vachterman/",
    facebookPage: "https://www.facebook.com/profile.php?id=100063616028917",
    description: "אני בעל תואר ראשון במדעי התזונה ומתמחה בתחומים של צמחונות, נשים, ילדים, סכרת, אירובי, קרוספיט, מכון כושר, אומניות לחימה, הריון ולאחר הריון. מאז שאני זוכר את עצמי עסקתי בספורט ואהבתי את זה, היה בלתי נמנע שהקישור הטבעי יקרה עם תזונה. אני מאמין שתהליך טוב הוא תהליך מבוקר, איכותי ושניתו להתמיד בו לאורך זמן. אין קיצורי דרך ואין ״זבנג וגמרנו״",
    course1: "תואר ראשון במדעי התזונה",
    course2: "מדריכי חדר כושר - וינגייט",
    course3: "DNA - DNOVA קורס פיענוח בדיקות"

  },
  { id: 4,
    title: "nutrition consultant haim",
    name: "חיים קנפו",
    profileImg: "/img/haimtrainer.avif",
    pageImg: "/img/trainersPage/haimTrainerPage.avif",
    aboutPage: "/trainers",
    instagramPage: "https://www.instagram.com/haim_knafo_ib/",
    facebookPage: "https://www.facebook.com/haim.knafo",
    description: "עובד במשרדי ישראלבודי השונים ברחבי הארץ משנת 2011. אהלן, אני חיים ואני המנהל המקצועי של מחלקת פגישות ייעוץ ברשת ישראלבודי. ומתמחה בעיצוב וחיטוב הגוף, הרזיה ועלייה במסת השריר. בין השאר גם בפיתוח הגוף למטרות שונות. אני מאמין כשיש מסגרת מתוכננת ומותאמת, התמדה וסבלנות, כל אחד יכול להגיע לתוצאה, בהתאם לרמת ההשקעה והפוטנציאל האישי",
    course1: "מאמני כושר ובריאות - ביה״ס למאמנים בוינגייט",
    course2: "תזונת ספורט - קמפוס שיאים",
    course3: "מדריך יסודות הרמות אולימפיות - קמפוס שיאים",
    course4: "טיפוח יציבה - יואל שמואלי",
    course5: "נטורופתיה, עיסוי שוודי, עיסוי רפואי, שיאצו - וינגייט",
    story1: "השמנה - גנטיקה? או פשוט הרגלים? כל התשובות",
    story2: "תקופת שימור",
    story3: "לרשימת כל הכתבות שלי - לחצו כאן",
    hrefStory1: "https://www.israelbody.org/articles/obesity-genetics-or-simply-habits",
    hrefStory2: "https://www.israelbody.org/articles/retention-period",
    hrefStory3: "https://www.israelbody.org/tags/haim-knafo-posts"

  },
  
  { id: 5,
    title: "nutrition consultant ron",
    name: "רון פוריש",
    profileImg: "/img/rontrainer.avif",
    pageImg: "/img/trainersPage/ronTrainerPage.avif",
    aboutPage: "/trainers",
    instagramPage: "https://www.instagram.com/ronforish/",
    facebookPage: "https://www.facebook.com/ron.forish/",
    description: "דיאטן קליני ומאמן כושר, אוהב לעבוד ולתת שירות חם ללקוחות שלי, מכור לחדר כושר ורכיבה באופניים, מאמין שכל אחד ואחת יכולים להגיע רחוק בעזרת דיאטה שפויה ומאוזנת המתאימה לאורח החיים האישי שלנו",
    course1: "תואר ראשון במדעי התזונה",
    course2: "קורס אימון מתקדם",
    course3: "קורס הפרעות אכילה"
  },
  { id: 6,
    title: "nutrition consultant emil",
    name: "אמיל גסנוב",
    profileImg: "/img/emiltrainer.avif",
    pageImg: "/img/trainersPage/emilTrainerPage.avif",
    aboutPage: "/trainers",
    instagramPage: "https://www.instagram.com/emil_gasanov/",
    facebookPage: "https://www.facebook.com/emil.gasanov",
    description: "אני מאמין שדיאטה טובה זו דיאטה שמתאימה להעדפות המטופל, לחיי היום יום שלו וללוח הזמנים שלו. דיאטה שהמטופל יוכל להתמיד בה לאורך זמן. דיאטה טובה נתפרת אישית לכל אחד",
    course1: "תואר ראשון במדעי התזונה",
    course2: "תואר שני במדעי התזונה - התמחות בהפרעות אכילה"
  },
];

export default trainersData;
